_wandb:
    value:
        cli_version: 0.21.1
        e:
            s71gj8s5r7qcx0bofvbod9diyg3pnxuv:
                codePath: test_gnn_v2.ipynb
                codePathLocal: test_gnn_v2.ipynb
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999396732928"
                        used: "828553641984"
                email: jyk.snuai@gmail.com
                executable: c:\Users\Junyoung Kim\.conda\envs\pyg5090\python.exe
                git:
                    commit: e60e3e782e65f65584ee5c7ac85997db8cfc08f4
                    remote: https://github.com/jk673/grapinnformer.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-024d439b-50ff-e90b-2414-06f639f12003
                host: DESKTOP-OU1MDPN
                memory:
                    total: "274741305344"
                os: Windows-10-10.0.22621-SP0
                program: c:\Users\Junyoung Kim\Desktop\grapinnformer\test_gnn_v2.ipynb
                python: CPython 3.11.13
                root: c:\Users\Junyoung Kim\Desktop\grapinnformer
                startedAt: "2025-08-19T12:57:31.927475Z"
                writerId: s71gj8s5r7qcx0bofvbod9diyg3pnxuv
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.1
            "8":
                - 1
                - 3
            "12": 0.21.1
            "13": windows-amd64
batch_size:
    value: 1
epochs:
    value: 75
feat_dim:
    value: 8
grad_clip:
    value: 5
loss_weights:
    value:
        data: 1
        lap: 0.01
        tv: 0.05
lr:
    value: 0.0001
model:
    value: BoundaryGraphNet
optimizer:
    value: Adam
target_dim:
    value: 1
use_tv:
    value: true
weight_decay:
    value: 1e-05
